### ISSUE TITLE
Demo & App are different features

### ISSUE THREAD

**Issue by PonlorkBeang** [codenteq/laerx#17]
Dear Author,

Your Demo & app are different features,
I deploy in my local PC and I see a few features, Companies, Uses, Question Bank, Marketing & System Settings, but Companies & users unable to create because of missing some information that require to create.
I also don't see change Language option in app

**Comment by ahmetarsiv** [comment]
@PonlorkBeang Hello, in our project, the Administrator language change feature has not been added, so it is closed for use, but there is a multi-language feature for other administrators.

Don't forget to update the project!

To create a user, comment the line I directed on your local computer //
https://github.com/codenteq/laerx/blob/master/app/Services/GlobalService.php#L41

**Comment by PonlorkBeang** [comment]
Noted with thanks

នៅថ្ងៃទី អាទិត្យ 21 សីហា 2022 នៅម៉ោង 5:33 PM Ahmet Arşiv <
***@***.***> បានសរសេរ៖
