### ISSUE TITLE
Method Index Doesn't Exists

### ISSUE THREAD

**Issue by dayCod** [codenteq/laerx#28]
# Bug Report

## Issue Description
the error appears when a user with the teacher type logs in

## Preconditions
there is no index method in the home controller

## Actual Result
Method App\Http\Controllers\HomeController::index does not exist. - Error (BadMethodCallException)

## Expected Result
bring up the page concerned with the user teacher type

**Comment by ahmetarsiv** [comment]
Hi @dayCod 

The error specified when I provided the test did not return, your problem may be from the cache in your browser. If you encounter an error in the teacher panel once again, you can indicate it with screenshots.

I created a demo user for you to see on the live server
[Dev Laerx](https://dev-laerx.codenteq.com/)
user: 06777777777
password: admin123
