### ISSUE TITLE
Demo Paswords

### ISSUE THREAD

**Issue by emreakay** [codenteq/laerx#3]
Hi,

how can i login to Demo app?
can you share paswords pls?

**Comment by ahmetarsiv** [comment]
Hello @emreakay 

We have created a wiki for student demo login information.

Click the link
https://github.com/codenteq/laerx/wiki/Demo-login-information

**Comment by emreakay** [comment]
hi @ahmetarsiv 
i have got an auth error

**Comment by ahmetarsiv** [comment]
Hello, @emreakay 
Checked in, no problem
Please try again from a different browser

**Comment by emreakay** [comment]
from which url i can login to demo app?

**Comment by ahmetarsiv** [comment]
@emreakay 
https://demo.codenteq.com/

**Comment by emreakay** [comment]
@ahmetarsiv thanks.
demo url on the github readme is wrong by the way

**Comment by ahmetarsiv** [comment]
@emreakay 
Thank you for providing information.

**Comment by emreakay** [comment]
nice project, it will be better if you also add zoom integration feature

**Comment by ahmetarsiv** [comment]
@emreakay 
For this, open a new feature request. Don't forget the details!

**Comment by emreakay** [comment]
👍
