### ISSUE TITLE
Language pack issue

### ISSUE THREAD

**Issue by shadespotsunlink** [codenteq/laerx#30]
how do I change the admin dashboard interface to english? I don't understand how to use the language packs. I changed the locale in app.config, but it didn't do anything. Is there something I am missing? Thanks for any help and support.

**Comment by ahmetarsiv** [comment]
@shadespotsunlink Hello, please log in as an administrator and then go to example.com/admin/language page. Add the default languages:

- Turkish (tr)
- English (en)
- Arabic (ar)
- Persian (fa)

Once everything is completed, you can go to your profile page to change the interface language.
