### ISSUE TITLE
Sitem Çalışmaması

### ISSUE THREAD

**Issue by yasin2351** [codenteq/laerx#31]
Merhaba,
öncelikle emekleriniz için teşekkür ederiz. şimdi kurulum yaptım ama bir çok yeri çalışmıyor örnek admin üzerinden kullanıcı eklenmiyor şirket eklenmiyor bu konuda sorun nerde yardımcı olabilir misiniz?

**Comment by ahmetarsiv** [comment]
Merhaba @yasin2351 Codenteq açık kaynak yazılımlarına katkıda bulunduğun için teşekkür ederim. Kontrol ettiğimde herhangi bir problem göremedim. Lütfen sorunu daha açık ve net bir şekilde ifade eder misin? Örneğin ekran görüntüleri ve aldığın hataları bize bildirirsen sana yardımcı olabiliriz..

**Comment by yasin2351** [comment]
@ahmetarsiv Teşekkürler,
composer ile sıfırdan kurulum yapıldığında manager, teacher veya user kullanıcıları yok sadece admin kullanıcısı var ve sorunsuz giriş yapabiliyoruz, kullanıcı eklemek için ilk olarak şirket eklememiz gerekiyor şirket eklerken ülke şehir veya ilçe yok manuel olarak ekleme yaptık https://prnt.sc/858atpq0eaPu bu şekilde tüm verileri doldurduktan sonra https://prnt.sc/zL_6YGsgl9c- bir hata ile karışılaşıldı diyor, bu konuda yardımcı olurmusunuz.

**Comment by ahmetarsiv** [comment]
@yasin2351 Merhaba, uygulamayı yeniden test ederek problem olmadığına, kurulum tarafında veya konfigürasyon tarafında eksiklikler olduğunu düşünüyorum. Bunun için kurulum adımlarını yeniden izleyebilirsin.
